name: firefirestyle.html.page
description: html location lib
version: 0.0.1
dependencies:
 browser: any
 firefirestyle.location:
   git:
     url: https://github.com/firefirestyle/dart.location.git
 dart_to_js_script_rewriter: any
dev_dependencies:
  test: any
